config/routes.rb
Rails.application.routes.draw do
  root "posts#index"

  get "login" => "sessions#new", :as => :login
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy", :via => "delete"

  get "signup" => "users#new"
  resources :users, :only => [:create] do
    resources :posts, :only => [:index]
  end

  resources :posts do
    resources :comments, only: [:new, :create]
  end

  resources :comments, only: [:index, :edit, :update, :delete] do
    resources :comments, only: [:new, :create]
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
  belongs_to :author, class_name: "User"
  has_many :comments, class_name: "Comment", as: :commentable
  validates :body, presence: :true

  def time_since_creation
    ((Time.now - created_at) / 3600).round
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :author, class_name: "User"
  has_many :comments, as: :commentable

  validates :title, :body, presence: true

  def time_since_creation
    ((Time.now - created_at) / 3600).round
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts, foreign_key: :author_id
  has_many :comments, foreign_key: :author_id

  validates :first_name, presence: true
  validates :last_name,  presence: true
  validates :username,   presence: true, uniqueness: true
  validates :email,      presence: true, uniqueness: true
  validates :password,   presence: true, length: { minimum: 6 }

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :set_scope, only: [:index]
    before_action :set_commentable, only: [:new, :create]

  def index
    @comments = @scope.all
  end

  def new
    if session[:user_id]
      #@commentable
      @comment = Comment.new
    else
      @errors = ["You must be signed in to comment on a post"]
      redirect_to posts_path
    end
  end

  def create
    @comment = Comment.new(comment_params)
    @user = User.find_by(id: session[:user_id])

    if @commentable.comments << @comment && @user.comments << @comment
      redirect_to posts_path #switch
    else
      @errors = @comment.errors.full_messages
      render "new"
    end
  end

  def edit
    @user = User.find(session[:user_id])
    @comment = @comment.find_by(id: params[:id])
    if @comment.author.id == session[:user_id]
      render "edit"
    else
      @errors = ["You must be the author of the comment to edit"]
      redirect_to :back
    end
  end

  def update
    @comment = Comment.find_by(id: params[:id])
    if @comment.update_attributes(comment_params)
      redirect_to @comment
    else
      @errors = @comment.errors.full_messages
      render "edit"
    end
  end

  def destroy
    @user = User.find_by(id: session[:user_id])
    @comment = Comment.find_by(id: params[:id])
    @comment.destroy if @user.id == @post.author.id
    redirect_to user_posts_path(@user)
  end

  protected

  def set_scope
    @scope ||= params[:user_id] ? Comment.where(author: params[:user_id]) : Comment
  end

  def set_commentable
    @commentable =  if params[:post_id]
                      Post.find_by(id: params[:post_id])
                    else
                      Comment.find_by(id: params[:comment_id])
                    end
  end

  private

    def comment_params
      params.require(:comment).permit(:body)
    end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_scope, only: [:index]
  # before_action :set_scope, only: [:index, :edit, :show]


  def index
    @posts = @scope.all
    render "index"
  end

  def new
    if session[:user_id]
      @post = Post.new
      render "new"
    else
      @errors = ["You must be signed in to create a post"]
      redirect_to posts_path
    end
  end

  def create
    @post = Post.new(post_params)
    @user = User.find_by(id: session[:user_id])

    if @user.posts << @post
      redirect_to posts_path
    else
      @errors = @post.errors.full_messages
      render "new"
    end
  end

  def show
    @post = Post.find_by(id: params[:id])
    render "show"
  end

  def edit
    @user = User.find(session[:user_id])
    @post = Post.find(params[:id])
    if @post.author.id == session[:user_id]
      render "edit"
    else
      @errors = ["You must be the author of the post to edit"]
      redirect_to :back
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      redirect_to @post
    else
      @errors = @post.errors.full_messages
      render "edit"
    end
  end

  def destroy
    @user = User.find(session[:user_id])
    @post = Post.find(params[:id])
    puts @user.id == @post.author.id
    @post.destroy if @user.id == @post.author.id
    redirect_to user_posts_path(@user)
  end

  protected

  def set_scope
    @scope ||= params[:user_id] ? Post.where(author: params[:user_id]) : Post
  end

  private

    def post_params
      params.require(:post).permit(:title, :body)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
    render "new"
  end

  def create
    user = User.find_by_username(params[:user][:username])
    if user && user.authenticate(params[:user][:password])
      session[:user_id] = user.id
      redirect_to user_posts_path(user)
    else
      @errors = ["You have entered an invalid username/password"]
      render "new"
    end
  end

  def destroy
    session.clear
    redirect_to "root"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render "new"
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_posts_path(@user)
    else
      @errors = @user.errors.full_messages
      render "new"
    end
  end

  private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :username, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.erb
<article id="<%= comment.id %>">
  <p>
    <span class="user"><%= link_to comment.author.username, user_posts_path(comment.author) %></span>
    <span class="time-since-creation"><%= comment.time_since_creation %> hours ago</span>
  </p>
  <p class= "comments">
    <%= comment.body %>
    <span><%= link_to "[edit]", edit_comment_path(comment) %></span>
    <span><%= link_to "[comment]", new_comment_comment_path(comment) %></span>
    <span><%= button_to "[delete]", comment_path(comment), :method => :delete, data: {confirm: "Are you sure?"} %></span>
    <p>
      <a href="#">link here</a>
    </p>
    <p class="comments">
    <% if comment.comments.any? %>
      <% comment.comments.each do |current_comment| %>
      <%= render partial: "comments/comment", locals: {comment: current_comment} %>
      <% end %>
    <% end %>
    </p>
  </p>


</article>

app/views/comments/_form.html.erb
<%= form_for [@commentable, @comment] do |f| %>
  <%= f.text_area :body,     placeholder: "body"  %>
  <%= f.submit "Comment!" %>
<% end %>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>
<%= render "form" %>
<a href="#">Back</a>

app/views/comments/index.html.erb
<div class="post-container">
    <%= render @comments %>
</div>

app/views/comments/new.html.erb
<h1>Create New Comment</h1>
<%= render "form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HackerNews</title>
  <%#stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <% javascript_include_tag 'application' %>
  <%#csrf_meta_tags %>
</head>
<body>
<header>
  <h1>Hacker News</h1>
  <p>
    <a href="<%= new_post_path %>">new</a>
    <a href="#">comments</a>
    <a href="#">popular</a>
    <a href="<%= login_path %>">login</a>
  </p>
</header>

<% if @errors %>
  <% @errors.each do |error| %>
    <p><%= error %></p>
  <% end %>
<% end %>

<section class="main">
  <%= yield %>
</section>

<pre>
  <% if session %>
  <%= "session[:user_id]: #{session[:user_id]}" %>
  <% end %>
</pre>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <%= f.text_field :title,   placeholder: "title"  %>
  <%= f.text_area :body,     placeholder: "body"  %>
  <%= f.submit "Post It!" %>
<% end %>

app/views/posts/_post.html.erb
<article id="<%= post.id %>">
  <h2><%= link_to post.title, post_path(post) %></h2>
  <p>
    <span class="user"><a href="<%= user_posts_path(post.author) %>"><%= post.author.username %></a></span>
    <span class="time-since-creation"><%= post.time_since_creation %> hours ago</span>
  </p>
  <p>
    <%= post.body %>
    <span><%= link_to "[edit]", edit_post_path(post) %></span>
    <span><%= link_to "[comment]", new_post_comment_path(post) %></span>
    <span><%= button_to "[delete]", post_path(post), :method => :delete, data: {confirm: "Are you sure?"} %></span>
  </p>
  <p>
    <a href="#">link here</a>
  </p>
  <p>
    <% if post.comments %>
      <% post.comments.each do |current_comment| %>
      <%= render partial: "/comments/comment", locals: {comment: current_comment, post: post} %>
      <% end %>
    <% end %>
  </p>
</article>

app/views/posts/_post_row.html.erb
<article id="<%= post.id %>">
  <h2><a href="<%= post_path(post) %>"><%= post.title %></a></h2>
  <p>
    <span class="user"><a href="<%= user_posts_path(post.author) %>"><%= post.author.username %></span>
    <span class="time-since-creation"><%= post.time_since_creation %> hours ago</span>
  </p>
  <p>
    <%= post.body %>
    <span><a href="<%= edit_post_path(post) %>">[edit]</a></span>
  </p>
  <p>
    <a href="#">link here</a>
  </p>
</article>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= render "form" %>
<a href="#">Back</a>

app/views/posts/index.html.erb
<div class="post-container">
    <%= render @posts %>
</div>

app/views/posts/new.html.erb
<h1>Create New Post</h1>
<%= render "form" %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= f.text_field :first_name,   placeholder: "first name"  %>
  <%= f.text_field :last_name,    placeholder: "last name"  %>
  <%= f.text_field :username,     placeholder: "username"  %>
  <%= f.email_field :email,       placeholder: "email"  %>
  <%= f.password_field :password, placeholder: "password"  %>
  <%= f.submit "Sign Up!" %>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>
<%= render "form" %>